name: site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  push:
    branches:
      - master
    paths:
      - .github/workflows/site.yml
  repository_dispatch:
    types: [forward-push]
  workflow_dispatch:
    
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Build HTML site
      shell: pwsh
      run: |
        git clone https://github.com/axmolengine/axmol.git
        git -C axmol checkout dev
        ./axmol/tools/ci/build-site.ps1
        ./redirect.ps1 'https://axmol.org/' ./axmol/docs/dist/axmol/index.html
    
    # Deploy HTML site to GitHub Pages
    - name: GH Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./axmol/docs/dist/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: gh-pages
        cname: axmol.org
    # Deploy HTML site to netlify Pages
    - name: Netlify Pages Deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./axmol/docs/dist2/
        enable_jekyll: false
        allow_empty_commit: false
        force_orphan: true
        publish_branch: netlify-pages
